name: AI Agent -> Medium Blog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate_blog_post:
    if: contains(github.event.head_commit.message, 'ai-blog') && github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    env:
      HF_MODEL: mistralai/Mistral-7B-Instruct-v0.2
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          pip install requests langchain langchain-openai langchain-community huggingface_hub transformers langgraph pydantic
      
      - name: Run AI Agent using LangChain
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          python ai_medium_agent.py
      
      - name: Run AI Agent using LangGraph
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          python ai_agent_langgraph.py

      
      - name: Commit medium.md
        run: |
          git add .
          git status
          git config --global user.name "Gaurav0807"
          git config --global user.email "gauravrawat141999@gmail.com"
          git commit -m "chore(ai-agent): generate medium.md" || echo "No changes"
          git push